### ISSUE TITLE
.pop()

### ISSUE THREAD

**Issue by rwilleynyc** [learn-co-curriculum/dsc-1-02-03-python-operators-functions-and-methods#1]
In the example, it appears [4, 5, 6, 7].pop() should be list_pop.pop()

**Comment by PeterBell** [comment]
Thanks so much Raymond - resolve with https://github.com/learn-co-curriculum/dsc-1-02-03-python-operators-functions-and-methods/commit/9cabe00bfdd4f5576b1653060b09437914111f29
