### ISSUE TITLE
Spelling error in first sentence

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/dsc-1-02-03-python-operators-functions-and-methods#2]
"In this lesson, we're going to **instroduce** some features..."

**Comment by Socjon** [comment]
"It is important to note the return value from each of these methods is not the **resultying** list."

**Comment by PeterBell** [comment]
Thanks so much - resolve with https://github.com/learn-co-curriculum/dsc-1-02-03-python-operators-functions-and-methods/commit/9cabe00bfdd4f5576b1653060b09437914111f29
